version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-gestao-financeira
    environment:
      POSTGRES_DB: gestao_financeira
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
